Description: >
    This template deploys the Imagetrends application on EC2 instances within an Autoscaling Group, behind a load balancer, with an Aurora MySQL database.

    Last Modified: 5th November 2018
    Author: Scott Horsfield <shhorsfi@amazon.com>

Parameters:

    DBName:
        Description: Imagetrends Database Name
        Type: String
        Default: imagetrends

    DBUser:
        Description: Imagetrends Database User
        Type: String
        Default: imagetrends
        
    DBPassword:
        Description: Imagetrends Database User Password
        Type: String
        Default: imagetrends

    KeyName:
        Description: Name of an existing EC2 KeyPair to enable SSH access to the app instances.
        Type: AWS::EC2::KeyPair::KeyName
        ConstraintDescription: must be the name of an existing EC2 KeyPair.

    InstanceType:
        Description: AppInstance EC2 instance type
        Type: String
        Default: t2.small
        AllowedValues:
        - t2.nano
        - t2.micro
        - t2.small
        - t2.medium
        - t2.large
        ConstraintDescription: must be a valid EC2 instance type.

    DBInstanceType:
        Description: AppDatabase DB instance type
        Type: String
        Default: db.t2.small
        AllowedValues:
        - db.t2.small
        - db.t2.medium
        ConstraintDescription: must be a valid DB instance type.

    SSHLocation:
        Description: The IP address range that can be used to SSH to the app instances.
        Type: String
        MinLength: '9'
        MaxLength: '18'
        Default: 0.0.0.0/0
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
        ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/imagetrends-sample-application/distributed-nested/vpc.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VpcCIDR: 10.180.0.0/16
                AppSubnet1CIDR: 10.180.8.0/21
                AppSubnet2CIDR: 10.180.16.0/21
                DatabaseSubnet1CIDR: 10.180.24.0/21
                DatabaseSubnet2CIDR: 10.180.32.0/21

    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/imagetrends-sample-application/distributed-nested/security-groups.yaml
            Parameters: 
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                SSHLocation: !Ref SSHLocation

    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/imagetrends-sample-application/distributed-nested/load-balancers.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.AppSubnets
                SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

    ASG:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/imagetrends-sample-application/distributed-nested/autoscaling-group.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                InstanceType: !Ref InstanceType
                ClusterSize: 2
                VPC: !GetAtt VPC.Outputs.VPC
                SecurityGroup: !GetAtt SecurityGroups.Outputs.AppHostSecurityGroup
                Subnets: !GetAtt VPC.Outputs.AppSubnets
                KeyName: !Ref KeyName
                AppTargetGroup: !GetAtt ALB.Outputs.TargetGroup
                PrimaryInstanceName: !GetAtt Database.Outputs.PrimaryInstanceName
                PrimaryInstancePort: !GetAtt Database.Outputs.PrimaryInstancePort
                ImageUploadBucket: !GetAtt ImageUploadBucket.Outputs.ImageUploadBucket

    ImageUploadBucket:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/imagetrends-sample-application/distributed-nested/bucket.yaml

    Database:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-us-west-2.amazonaws.com/imagetrends-sample-application/distributed-nested/database.yaml
            Parameters:
                DBInstanceType: !Ref DBInstanceType
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.DatabaseSubnets
                SecurityGroup: !GetAtt SecurityGroups.Outputs.RDSInstanceSecurityGroup
                DBName: !Ref DBName
                DBUser: !Ref DBUser
                DBPassword: !Ref DBPassword

Outputs:

    ImagetrendsAppUrl: 
        Description: The URL endpoint for the Imagetrends application
        Value: !Join [ "", [ "http://", !GetAtt ALB.Outputs.LoadBalancerUrl]]